### ISSUE TITLE
Pkggen.exe missing

### ISSUE THREAD

**Issue by Trinetra** [ms-iot/iot-adk-addonkit#103]
Hi, createpkg.cmd in tools calls pkggen.exe, which is missing! Also, the environment variables %KITSROOT% and %IOTADK_ROOT% have to be manually edited in setenv.cmd. Please mention that somewhere!

**Comment by IoTGirl** [comment]
Please see https://social.msdn.microsoft.com/Forums/en-US/8f18840f-3e39-4a97-900e-c15c502c00c7/pkggenexe-missing-when-run-inf2cabcmd-to-create-a-driver-package?forum=WindowsIoT
