### ISSUE TITLE
Never install my application

### ISSUE THREAD

**Issue by Monigass** [ms-iot/iot-adk-addonkit#104]
Hi, I have a problem, when I build an image and flash it to the SD memory, the Raspberry pi doesn't even install my app, it only restarts itself.

I have this isue on 15063 version only, the past versions worked perfectly.

What I am doing wrong? 

I've also tried the "Lab 1a: Create a basic image" but I can not see any application.

**Comment by IoTGirl** [comment]
Hi @Monigass , 
With the very little information you have provided it is impossible to know but you state that previous versions are working and the latest is not so my first suspicion is that you do not have the tools for 15063 installed, only the tools for prior builds.

If you want further assistance you will need to provide far more detail as to your setup, the steps you take and the various error logs you have reviewed.

Sincerely,
IoTGirl

**Comment by parameshbabu** [comment]
@Monigass, do you install your app using the provisioning package ( using updated newappxpkg.cmd )?

**Comment by Monigass** [comment]
@parameshbabu, Yes, I follow this steps:

https://docs.microsoft.com/es-es/windows-hardware/manufacture/iot/deploy-your-app-with-a-standard-board

I've done this with a Test package, but I can't with the PreinstallKit version (from my Windows Dev Center account): 

https://developer.microsoft.com/en-us/windows/iot/docs/store

Thaks.

**Comment by parameshbabu** [comment]
@Monigass, I found an issue with the license installation for the store apps and this is now fixed. 
Use the latest version of the develop branch ( main change is in appx2pkg.cmd that gets called from newappxpkg.cmd). Let me know if this works for you and I can close this issue.

**Comment by parameshbabu** [comment]
Fix part of PR #106 . The master branch will be also updated shortly.

**Comment by parameshbabu** [comment]
Use PR #107 for the master branch for this fix.

**Comment by IoTGirl** [comment]
@Monigass Can you please confirm this fix addresses your issue?

**Comment by parameshbabu** [comment]
Closing.
