### ISSUE TITLE
How to get an especific versión of SO for to build the image

### ISSUE THREAD

**Issue by juasmal** [ms-iot/iot-adk-addonkit#117]
Hello,

Label as a question please.

i'm wondering how can i get the base for tu build and image with the specific versión of the SO.

I would like to build the image over the versión 10.0.15063.414. 

When i build the image i got the 10.0.15063.0. And i would like to disable the updates (i'm using the w10 iot core pro with license).

Thanks!

PD: i just download the latest iot-adj-addonkit version and this weekend i'll test the working pending. that i have

**Comment by parameshbabu** [comment]
Please look into Microsoft OEM website for the core kits with servicing fixes.
