### ISSUE TITLE
newupdate.cmd not found

### ISSUE THREAD

**Issue by IotCore-Developer** [ms-iot/iot-adk-addonkit#130]
When I try to create an update to test the command cannot be found.

See tutorial :

https://docs.microsoft.com/en-us/windows-hardware/service/iot/updating-iot-core-apps#Test_and_track_the_update

Step 1.

How must this be done without this tool ?

**Comment by parameshbabu** [comment]
@IotCore-Developer this command had been taken off as the mechanism was changed. We will add an equivalent of this soon and update the doc page as well. Stay tuned.

**Comment by IotCore-Developer** [comment]
Hi,

When Will this Be realized?
Is IT a Matter of days, weeks?

Best regards

On Wednesday, September 13, 2017, Paramesh Babu Rengarao Thyada <
notifications@github.com> wrote:
> @IotCore-Developer this command had been taken off as the mechanism was
changed. We will add an equivalent of this soon and update the doc page as
well. Stay tuned.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or mute the thread.<
https://ci6.googleusercontent.com/proxy/ax8PZbh8Klb19zV8zWAjKLBIlb9d8hMFAOwzViKqLZZWT7Bxd9ponUj8gLLd7QKNPQ9HVtUukXy5690t-nZtn_Byn0QqVlsRg28IpujuAzH48IyAWD6_NnDwDOyAee8N5Omn6_6IX1ufLi6zlIgm2nrf97zt5Q=s0-d-e1-ft#https://github.com/notifications/beacon/AeYvV2ayWdesnFvYvwxJND7IDn3cTYH8ks5siBhagaJpZM4PTkxi.gif>

**Comment by parameshbabu** [comment]
@IotCore-Developer this should be available in a months time. early oct.

**Comment by IotCore-Developer** [comment]
Ok thx for the update

Sent from Mail for Windows 10

**Comment by IotCore-Developer** [comment]
Hi,

What  is the status of this update ?

Best Regards

Sent from Mail for Windows 10

**Comment by parameshbabu** [comment]
newupdate.cmd / buildupdates.cmd are available now. The instructions to use will be posted soon, listed here in a short summary
1. newupdate updatename version
2. set USEUPDATE=updatename
3. newappxpkg to create a new version of the appx package - use same name as the original package. The new pkg will be created in the updatename directory.
4. bp all - build base packages, 
5. buildimage - this will build the  update packages (set with USE_UPDATE flag) and copy them in the right folder to create the image with this update package.

**Comment by IotCore-Developer** [comment]
Ok thank you for your infomation.

On Tuesday, October 17, 2017, Paramesh Babu Rengarao Thyada <
notifications@github.com> wrote:
> newupdate.cmd / buildupdates.cmd are available now. The instructions to
use will be posted soon, listed here in a short summary
>
> newupdate updatename version
> set USEUPDATE=updatename
> newappxpkg to create a new version of the appx package - use same name as
the original package. The new pkg will be created in the updatename
directory.
> bp all - build base packages,
> buildimage - this will build the update packages (set with USE_UPDATE
flag) and copy them in the right folder to create the image with this
update package.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or mute the thread.<
https://ci6.googleusercontent.com/proxy/KqMfDj6fdUUScGMPrB4kk2Vi0uzknjtgK0-T0IYNRial-vPr2aC8BzVYX57SEnYd6QuCOS2gXP10ImVac-JWgNyrYEwycfTnHptTmS7MwBE2A2lDQCC9e3Cj5dNO1O3gHd_fdV9L0ExOFcRf-RXlUoGsKAGuOQ=s0-d-e1-ft#https://github.com/notifications/beacon/AeYvV9gx0qkfKi2NFQznzx0EG0lqIgDxks5stRcegaJpZM4PTkxi.gif>
