### ISSUE TITLE
setOEM.cmd causes build failure

### ISSUE THREAD

**Issue by mjmeans** [ms-iot/iot-adk-addonkit#140]
If you "set OEM_NAME=Fabrikam, Inc." then build fails. I don't know if it is the comma or the period or the space that is causing this problem. However, if I use "set OEM_NAME=FabrikamInc" it works, but that is not the correct company name. Is punctuation allowed?

Either way, the lab should be updated to tell people the limitations of this parameter.

**Comment by parameshbabu** [comment]
This name is used as a prefix for the component package file names and no special characters are allowed here. I'll add that to the doc.
