### ISSUE TITLE
Missing Recovery.MBR-BcdEdit, etc.

### ISSUE THREAD

**Issue by mjmeans** [ms-iot/iot-adk-addonkit#155]
The repo includes MBR layouts for -R but no Recovery package(s) for MBR.

**Comment by parameshbabu** [comment]
Recovery packages are same for both MBR/GPT. However there is so sample yet show-casing the recovery on the MBR layout.. it is in the backlog for now.

**Comment by mjmeans** [comment]
I have copied the GPT recovery packages to MBR and changed GPT to MBR wherever it was found. I added it to the product and was able to buildimage and buildrecovery successfully. However, when I powershell into the device and run the recovery script, the RPi boots into an error message. I posted the error on the Windows IoT Forums with no response yet. I'm assuming that the cmd scripts from the GPT package won't work for MPR.

**Comment by parameshbabu** [comment]
ok looks like there is more changes required in the scripts to handle the MBR partition guids. We will take a look a that and update.

**Comment by mjmeans** [comment]
Are there any updates on this issue?

**Comment by parameshbabu** [comment]
With #225 you should be able to perform recovery on rpi platform. Please use Recovery-MBR-BCD package instead of the GPT-BCD.
