### ISSUE TITLE
Are community BSPs accepted? 

### ISSUE THREAD

**Issue by VladimirAkopyan** [ms-iot/iot-adk-addonkit#160]
If I were to create a BSP for a commercial off-the-shelf device, would the PR be accepted? 
I have recently tested Windows IoT on a tablet Linx1010 and it works very well. Or do I have ot host that separately?

**Comment by parameshbabu** [comment]
@VladimirAkopyan , can you provide more details on the BSP ? 
To answer to the question , yes we do support this and accept this if it meets the license terms on this GitHub.

**Comment by parameshbabu** [comment]
With the new code structure, you can publish your BSPs in your own repo's and the tools are made easy to import them in the workspace. Please follow the BSP folder structure and the contents as per the sample RPi_BSP.
