### ISSUE TITLE
OOBE app closes before oem customizations completes

### ISSUE THREAD

**Issue by mjmeans** [ms-iot/iot-adk-addonkit#167]
So what happens is that the OEM app appears on the screen before Custom.Cmd (oemcustomization.cmd) finishes. I have an oemcustomization.cmd script that has an additional set of commands after the firstbootdone if block, but before the Recovery.BcdEdit commands. It calls a powershell script that checks to make sure the computer name is set to a unique name according to a hardware serial number and if it doesn't match what it is supposed to be it changes the computer name and reboots. What I'm seeing is that Windows boots and the "please wait while we get things ready" screen appears. I see it appear in Windows IoT Dashboard with a default computer name of minwinpc. Then my app appears. Then several seconds later the system reboots and when it comes back up the correct unique computer name is set.

So my app is appearing on the screen before oemcustomization.cmd finishes. Is there a solution to this so that my app does not appear until oemcustomization.cmd finishes?

**Comment by parameshbabu** [comment]
The OEM Customisation.cmd and the provisioning process are run in parallel and the app appears as the provisioning process completes. If you want to control when the app gets installed, you can do the manual provisioning process ( calling provtool.exe <ppkg name> ) in the oemcustomizations.cmd, note that in this case, you should copy the ppkg to a different directory (say c:\OEM )
