### ISSUE TITLE
Feature Request:

### ISSUE THREAD

**Issue by mjmeans** [ms-iot/iot-adk-addonkit#168]
I posted an issue over [here](https://social.msdn.microsoft.com/Forums/en-US/380d6ff5-f844-4be8-a983-ccbd506a2544/sqmclient-preprovisiondevicecmd-question?forum=WindowsIoT#033a6da2-3464-409e-9c58-4cb0b1304185) about this. If you write your custom flash.ffu using the iot core dashboard, it creates a PreProvisionDevice.cmd in the root of the SD Card. This cmd runs and among other things sets HKLM\Software\Microsoft\SQMClient\MachineId to a new random Uuid and then deletes itself. This is a problem for mass duplication of flash.ffu images for production, or distribution using dism to write the image. I think an ideal solution would be for oemcustomizations.cmd to write that reg key in the first boot section. But for that to work, the cmd shell would need some way to generate a new Uuid. Is this possible?

**Comment by parameshbabu** [comment]
Please ignore the PreProvisionDevice.cmd - this is added mainly to interface with the IoT Dashboard, passing the wifi settings and user credentials etc. The MachineId was added for some reason and didnt get removed i guess. This will be generated at boot anyway and the device will get an unique id always.
 For mass production you can use the custom ffu directly and can distribute using dism.
