### ISSUE TITLE
IOT_NANORDPSERVER not working

### ISSUE THREAD

**Issue by mjmeans** [ms-iot/iot-adk-addonkit#178]
On Rpi 3. IOT_NANORDPSERVER only connects the mouse. The PC doesn't see the image of the screen but the mouse movement on the PC moves the mouse on the device.

**Comment by anphel31** [comment]
This is a known issue with the latest IoTCore release and Raspberry Pi. This is being investigated but unfortunately I don't have an ETA for the fix.

**Comment by saraclay** [comment]
There's been an update since this comment was made. Is this still an issue for you both?

**Comment by mjmeans** [comment]
I have not been working with RPi for the last few months, so I don't know.

**Comment by saraclay** [comment]
Ok. I will close this for now. @mjmeans, please open an issue if you run into anything else.
