### ISSUE TITLE
Featuremerge fails during buildimage process

### ISSUE THREAD

**Issue by fljSoft** [ms-iot/iot-adk-addonkit#186]
Hello

I am attempting to create a Windows 10 Iot image for a RPI3.

I've been following the guide: https://docs.microsoft.com/en-us/windows-hardware/manufacture/iot/iot-core-manufacturing-guide

Lab 1a: Create a basic image:

Everything went fine until the last step to build the image.
Error : Build failed. See Log for details.

In the log I can find: 

Creating ScInfoScreen test Image
Build Start Time :  8:42:54,47
Building Packages with product specific contents with version 10.0.0.0
 Processing Registry.Version.wm.xml
 Processing Custom.Cmd.wm.xml
 Processing ScInfoScreen
 Processing Provisioning.Auto.wm.xml
Running FeatureMerger for OEM packages
  Exporting OEMFM files
  Processing OEMFMFileList.xml
Running FeatureMerger for rpi2
  Exporting rpi2 FM files
  Processing rpi2FMFileList.xml
  [91mError: Featuremerger failed for rpi2FMFileList.xml. See C:\iot-adk-addonkit-master\Build\arm\buildfm_bsp_rpi2.log[0m
Creating Image...
Microsoft (C) imageapp 10.0.10011.16384

ImageApp!ConfigureServicingStackLogging: Failed initializing WdsCore.dll.
ImageApp: Setting CPU Type to 'arm'.
info: Imaging: Reading the OEM Input XML file...
info: FeatureAPI: Successfully validated the OEM Input XML: C:\iot-adk-addonkit-master\Source-arm\Products\ScInfoScreen\testOEMInput.xml
info: Imaging: Reading the FM XML file 'C:\iot-adk-addonkit-master\Build\arm\MergedFMs\RPi2FM.xml'...
fatal error : Imaging!ValidateInput: Failed to load Feature Manifest XML file C:\iot-adk-addonkit-master\Build\arm\MergedFMs\RPi2FM.xml:FeatureAPI!ValidateAndLoad: FeatureManifest file was not found: C:\iot-adk-addonkit-master\Build\arm\MergedFMs\RPi2FM.xml
fatal error : 	FeatureAPI!ValidateAndLoad: FeatureManifest file was not found: C:\iot-adk-addonkit-master\Build\arm\MergedFMs\RPi2FM.xml
info: Imaging: See Flash.cbs.log and Flash.csi.log for details.
info: Imaging: Performance Results:
info: 	Total Run Time:	00:00:00.1858600
info: 	Storage Stack Time:	00:00:00
ImageApp: Error log can be found at 'C:\IOT-AD~1\Build\arm\SCINFO~1\test\Flash.ImageApp.log'.
"CreateImage ScInfoScreen test" failed with error 1

when inspecting the second log for what cause Featuremerge to fail it says i'm missing packages.

`info: Trying to load file 'C:\iot-adk-addonkit-master\Build\arm\InputFMs\rpi2FMFileList.xml' as a FM file list ...
fatal error : Error: Missing package: C:\Program Files (x86)\Windows Kits\10\MSPackages\Retail\arm\fre\RASPBERRYPI.RPi2.BootFirmware.cab
fatal error : Error: Missing package: C:\Program Files (x86)\Windows Kits\10\MSPackages\Retail\arm\fre\RASPBERRYPI.RPi2.dwcUsbOtg.cab
fatal error : Error: Missing package: C:\Program Files (x86)\Windows Kits\10\MSPackages\Retail\arm\fre\RASPBERRYPI.RPi.LAN9500N650F.cab
fatal error : Error: Missing package: C:\Program Files (x86)\Windows Kits\10\MSPackages\Retail\arm\fre\RASPBERRYPI.RPi2.USBWIFI.cab
fatal error : Error: Missing package: C:\Program Files (x86)\Windows Kits\10\MSPackages\Retail\arm\fre\RASPBERRYPI.RPi2.RT.WLAN.cab
fatal error : Error: Missing package: C:\Program Files (x86)\Windows Kits\10\MSPackages\Retail\arm\fre\RASPBERRYPI.RPi.FT5406.Touch.cab
fatal error : Error: Missing package: C:\Program Files (x86)\Windows Kits\10\MSPackages\Retail\arm\fre\RASPBERRYPI.RPi.Wifi.bcmdhd63.cab
fatal error : Error: Missing package: C:\Program Files (x86)\Windows Kits\10\MSPackages\Retail\arm\fre\RASPBERRYPI.RPi.Wifi.bcmdhd63.cab
fatal error : Error: Missing package: C:\Program Files (x86)\Windows Kits\10\MSPackages\Retail\arm\fre\RASPBERRYPI.RPi.BtwSerialH5Bus.cab
fatal error : Error: Missing package: C:\Program Files (x86)\Windows Kits\10\MSPackages\Retail\arm\fre\RASPBERRYPI.RPi.BtwSerialH5Bus.cab
`

and correct there is nothing in that path its refering to in log.

At C:\Program Files (x86)\Windows Kits\10\MSPackages\Retail\

I've got a image "Windows10_IoTCore_RPi_ARM32_en-us_16299" which i ran but this didin't solve anything.

Where are those BSP packages I'am missing? and how do I get em?

**Comment by parameshbabu** [comment]
You will need the RPi BSP packages. See https://docs.microsoft.com/en-us/windows/iot-core/build-your-image/createbsps for the instructions.
