### ISSUE TITLE
Cannot add a file and a registry setting to an image!

### ISSUE THREAD

**Issue by Parsakarami** [ms-iot/iot-adk-addonkit#195]
I faced a problem when i want add some of static file like .txt files and other type of files to my costume image, I follow the instruction from the manufacturing guide in this [link](https://docs.microsoft.com/en-us/windows-hardware/manufacture/iot/add-a-registry-setting-to-an-image#span-idupdateyourfeaturemanifestspanspan-idupdateyourfeaturemanifestspanspan-idupdateyourfeaturemanifestspanupdate-your-feature-manifest), but when i use `buildpkg Registry.FilesAndRegKeys` command i got an error.
In log file this error written : **Package creation failed with error -1**

**Comment by parameshbabu** [comment]
Please look into the log file generated in the Build\arch\pkgs\logs directory to see the error. Most likely the path of the static files are incorrect.
