### ISSUE TITLE
no script for Bay Trail family

### ISSUE THREAD

**Issue by jkanounji** [ms-iot/iot-adk-addonkit#201]
There are convert scripts for Apollo Lake, Brasswell and Qualcomm , but not Bay Trail. Though this can be easily remedied by copying the BSW convert scripts and replacing all instances of BSW by BYT inside the script.

**Comment by parameshbabu** [comment]
Baytrail instructions are listed here https://docs.microsoft.com/en-us/windows/iot-core/build-your-image/createbsps ,

**Comment by bibble235** [comment]
I have forked this and added a script, also added a pull request. https://github.com/bibble235/iot-adk-addonkit

**Comment by parameshbabu** [comment]
Closing this issue as the pull request above has been integrated. Thanks.
