### ISSUE TITLE
Add recovery for raspberry Pi 3

### ISSUE THREAD

**Issue by VitorX** [ms-iot/iot-adk-addonkit#205]
**Environment**
Raspberry Pi 3 B with Win 10 Iot Core 

**Target**
Add recovery mechanism 

**Steps**

1. Follow [Add a recovery mechanism to your image](https://docs.microsoft.com/en-us/windows/iot-core/build-your-image/addrecovery) to build the recovery FFU successfully(Flash_Recovery.ffu).

2. Flash this ffu to the card, the win 10 iot core also boot successfully. 

3. Start the recovery the OS by running the command **f:\startrecovery.cmd**  from device portal
![untitled picture](https://user-images.githubusercontent.com/12635993/38007092-4d133e5c-327a-11e8-8154-a2392f11125f.png)

**Result**
Not able to boot. It stayed on  **Windows Boot Manager**  like figure blew:
![img_1889](https://user-images.githubusercontent.com/12635993/38006820-218bc3ae-3279-11e8-8839-c5b8ec8411c4.jpg)

So here is my questions, any help info is appreciate:

1. How can I make the recovery mechanism works for Raspberry Pi 3 with Win 10 Iot Core 
2. Can I trigger it before boot to the normal OS by press the key?
3. Is there any document about how the recovery mechanism will be triggered automatly?

**Comment by parameshbabu** [comment]
we will take a look at this and update

**Comment by parameshbabu** [comment]
With #225 you should be able to perform recovery on rpi platform. Please use Recovery-MBR-BCD package instead of the GPT-BCD.

**Comment by VitorX** [comment]
Thanks all for the help. I will test this issue and update whether it works:)

**Comment by VitorX** [comment]
@parameshbabu , @anphel31 
Thanks for your help, it woks well now:)

**Comment by alexiordan** [comment]
Why this functionality is not included in the standard image for Raspberry PI?
