### ISSUE TITLE
Powershell feature in Retail Image doesn't seem to allow remote connections

### ISSUE THREAD

**Issue by bderuijsscher** [ms-iot/iot-adk-addonkit#220]
When including the IOT_POWERSHELL feature and after successfully building a retail image, remotely connecting to the device yields a "connection refused" powershell error. Are there any other specific options to include in order to achieve a remote powershell connectivity?

Thanks in advance, regards

**Comment by parameshbabu** [comment]
Do you have administrator account enabled and password set? This can be done in the oemcustomization.cmd - see https://github.com/ms-iot/iot-adk-addonkit/blob/master/Templates/oemcustomization.cmd

**Comment by bderuijsscher** [comment]
There is not much difference compared to the Test image I have built. Of course with a much reduced featureset, here is an excerpt from the RetailOEMInput.xml:

 ```
<Features>
    <Microsoft>
      <Feature>IOT_EFIESP</Feature>
      <Feature>IOT_EFIESP_BCD_MBR</Feature>
      <Feature>IOT_DMAP_DRIVER</Feature>
      <Feature>IOT_GENERIC_POP</Feature>
      <Feature>IOT_POWERSHELL</Feature> <!-- Adds PowerShell -->
      <!-- Following two required for Appx Installation -->
      <Feature>IOT_UAP_OOBE</Feature>
      <Feature>IOT_APP_TOOLKIT</Feature>
      <!-- Sample Apps, remove this when you introduce OEM Apps -->
      <!-- <Feature>IOT_BERTHA</Feature> -->
      <!-- <Feature>IOT_ALLJOYN_APP</Feature> -->

    </Microsoft>
    <OEM>
      <!-- Include BSP Features -->
      <Feature>RPI2_DRIVERS</Feature>
      <Feature>RPI3_DRIVERS</Feature>
      <!-- Include OEM features -->
      <Feature>OEM_CustomCmd</Feature>
      <Feature>OEM_ProvAuto</Feature>
	  
	  <!-- MydentitySensor Specific -->
	  <Feature>OEM_MyCustom_ADDONS</Feature> <!-- Installs ACPI table file to enable TPM module access through SPI0 CS1 and adds Write Filter initialization after first boot -->
	  <Feature>AZUREDM_SERVICES</Feature> <!-- Installs Azure DM Proxy SystemConfigurator.exe as a service -->
	  <Feature>OEM_MyCustomSoftware</Feature> <!-- My Custom Software -->	  

    </OEM>
```

I did notice a Test only feature mentioned in the Manufacturing guide called IOT_ENABLE_ADMIN ([here](https://docs.microsoft.com/en-us/windows-hardware/manufacture/iot/iot-core-feature-list)), would this be appropriate?

**Comment by parameshbabu** [comment]
No do not use the iot_enable_admin as it is a test package not allowed to be used in a retail image.
Also that one sets default password to the device (p@ssw0rd).

The oeminput file looks good. You just need to add the ‘net user ...’ line in the oemcustomization.cmd file. That will enable administrator role and set the password you provide there. Then you should be able to access it via power shell.

Regards,
Paramesh
________________________________

**Comment by bderuijsscher** [comment]
Hello Paramesh,

thanks again for your assistance. I have retested and still I get an Access Denied when attempting to powershell into the retail imaged device. Here are my oemcustomization.cmd contents:

```
echo off
REM OEM Customization Script file
REM This script if included in the image, is called everytime the system boots.

reg query HKLM\Software\IoT /v FirstBootDone >nul 2>&1

if %errorlevel% == 1 (
    REM Enable Administrator User
    net user Administrator p@ssw0rd /active:yes
    if exist C:\Data\oobe (
        call folderpermissions.exe 'C:\Data\oobe -e'
    )
REM - Enable the below if you need secure boot/bitlocker
REM Enable Secureboot
REM if exist c:\IoTSec\setup.secureboot.cmd  (
REM    call c:\IoTSec\setup.secureboot.cmd
REM )

REM Enable Bitlocker
REM if exist c:\IoTSec\setup.bitlocker.cmd  (
REM    call c:\IoTSec\setup.bitlocker.cmd
REM )
    reg add HKLM\Software\IoT /v FirstBootDone /t REG_DWORD /d 1 /f >nul 2>&1
	
)

REM The below should be called on every boot
if exist C:\RecoveryConfig\Recovery.BcdEdit.cmd (
    call C:\RecoveryConfig\Recovery.BcdEdit.cmd
)

REM Set the crashdump file locations to data partition, set on every boot.
reg add "HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\CrashControl" /v DedicatedDumpFile /t REG_SZ /d C:\Data\DedicatedDumpFile.sys /f
reg add "HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\CrashControl" /v DumpFile /t REG_SZ /d C:\Data\MEMORY.DMP /f
```

This file is used both for Test and Retail images if I am not mistaken. Furthermore, when building a Test version i AM able to Powershell into the device, if building the Retail version it doesn't work.

What else can I do to determine where the issues are?

n.b. I have also included a Files and Registry package that should automatically enable access to a TPM module on through SPI0 CS1 (through adding the approriate ACPITABL.DAT file to System32 folder). Unfortunately this doesn't seem to work properly as well in Retail imaging mode, it does work in Test mode as well. Could there be a relationship?

Thanks again for any assistance.

**Comment by bderuijsscher** [comment]
Update: my bad, Powershell access is possible though only using explicit -Credential options. Apparently for a Test imaged device it would prompt me for credentials, in Retail mode the access can only be achieved by properly providing the credentials. 

However, this doesn't answer the problems with the TPM chip access though. Are there any other measures that need to be provided in order for the TPM access to be possible? Again, it does seem to work properly in test mode.

**Comment by bderuijsscher** [comment]
This issue can be closed, PowerShell is possible however there seems to be a problem with the Azure DM SystemConfigurator proxy which is unable to start in retail mode.

**Comment by parameshbabu** [comment]
I recommend to report the issue on the Azure DM GitHub for the retail mode issue. Thanks.
