### ISSUE TITLE
No certificates were found that met all the given criteria.

### ISSUE THREAD

**Issue by getStrong2016** [ms-iot/iot-adk-addonkit#242]
In the use of inf2cab, the last tip is "No certificates were found that met all the given criteria.". What is the reason, please?

**Comment by parameshbabu** [comment]
Maybe you are missing the test certificates used for signing. Run "installoemcerts" in the IoTCore shell to install the test certs.

**Comment by parameshbabu** [comment]
@getStrong2016  do you still have this issue?

**Comment by parameshbabu** [comment]
@getStrong2016  please reopen this issue if you still have problems. Closing
