### ISSUE TITLE
What is the "CUSTOM_CMD" and "PROV_AUTO" means?

### ISSUE THREAD

**Issue by moyanming** [ms-iot/iot-adk-addonkit#244]
The sample will be used for new product, but there are OEM features "CUSTOM_CMD" and "PROV_AUTO", does those should be "OEM_CUSTOM_CMD" and "OEM_PROV_AUTO"?
https://github.com/ms-iot/iot-adk-addonkit/blob/a6b43fb53a13d21380c5c4223c428eea711b658a/Source-arm/BSP/QCDB410C/OEMInputSamples/TestOEMInput.xml#L70

**Comment by parameshbabu** [comment]
No. Just include it as custom_cmd and prov_auto. Should be fine.

Regards,
Paramesh
________________________________

**Comment by parameshbabu** [comment]
Thanks for reporting. Will have the docs updated.

Regards,
Paramesh
________________________________

**Comment by parameshbabu** [comment]
On the docs on custom_cmd, you can use either one , preferably the one without oem_

It was kept to maintain backward compatibility

See oemcommonfm.xml


     
     <PackageFile Path="%PKGBLD_DIR%" Name="%OEM_NAME%.Custom.Cmd.cab">
       <FeatureIDs>
         <FeatureID>OEM_CustomCmd</FeatureID>
         <FeatureID>CUSTOM_CMD</FeatureID>
       </FeatureIDs>
     </PackageFile>
     <PackageFile Path="%PKGBLD_DIR%" Name="%OEM_NAME%.Provisioning.Auto.cab">
       <FeatureIDs>
         <FeatureID>OEM_ProvAuto</FeatureID>
         <FeatureID>PROV_AUTO</FeatureID>
       </FeatureIDs>
     </PackageFile>

Regards,
Paramesh
________________________________
