### ISSUE TITLE
Build Image is failing with WIN32(161) (Path specified is invalid) error on 4.4 toolkit

### ISSUE THREAD

**Issue by majidshaffi** [ms-iot/iot-adk-addonkit#247]
I am creating a Registry.Config packge in which I am packaging some files. These files have a destination to runtime.systemDrive which is C:\ but the build image is giving error that the path specified is invalid and it cannot resolve it.
I am using WDK and ADK of 16299 and the CoreKit version is 16299.64.

The image error log is pasted below:

{6/27/2018 6:24:09 AM} **Error: [00:10:22] Operation failed finalizing changes: HRESULT_FROM_WIN32(161)**
{6/27/2018 6:24:09 AM} Error: [00:10:22] onecore\base\cbs\mobile\iucore\iupartition.cpp, IUPartition::ProcessIndividualPackages, line 1250, Error  , Failed to finalize client, error is 0x800700A1
{6/27/2018 6:24:09 AM}  [00:10:22] Closing session ImgUpd_mainos_Commit
{6/27/2018 6:24:10 AM} Error: [00:10:22] onecore\base\cbs\mobile\iucore\iupartition.cpp, IUPartition::ProcessAllPackages, line 1375, Error  , Failed to process individual packages while Commit, error is 0x800700A1
{6/27/2018 6:24:10 AM} Error: [00:10:22] onecore\base\cbs\mobile\updatedll\lib\executeupdate.cpp, UpdateMain::Commit, line 1002, Error  , Failed to commit partition mainos, error is 0x800700A1.

The customization.xml for registry.config is as below. The cab file is building fine but in the build image it says the path is invalid which means its not resolving runtime.systemDrive macro:

        <file
            destinationDir="**$(runtime.systemDrive)**\OEMTools"
            source="C:\Files\CommandInvoker.exe"
			name = "CommandInvoker.exe"		/>

It is important that the CommandInvoker.exe needs to be in C:\OEMTools because of many reasons so thats why I am using this variable so that the file should be there in first bootup. Can anyone tell me where I am going wrong or suggest me another variable that might work instead and palce that file in C:\OEMTools.

The allowed variables in the OEM Package schema says that $(runtime.systemDrive) is allowed as a variable.

**Comment by parameshbabu** [comment]
If you need to put it in C:\, then please use $(runtime.bootDrive). See https://github.com/ms-iot/iot-adk-addonkit/blob/master/Common/ProdPackages/Recovery.WinPE/Recovery.WinPE.wm.xml for a sample.
