### ISSUE TITLE
image built succesfuly but screens shows graphic memory(collors of video card)

### ISSUE THREAD

**Issue by jelletaal** [ms-iot/iot-adk-addonkit#252]
i created an [issue](https://github.com/MicrosoftDocs/commercialization-public/issues/213) on the commercialization-public github and I thought it should have been here... does anybody know what I did  wrong and how to fix?

**Comment by anphel31** [comment]
I don't see any errors in the build log.
Can you confirm that you're using a good SD card, and it was flashed properly? Perhaps download one of the prebuilt Raspberry PI images and confirm that is booting on your device/SD card.
https://developer.microsoft.com/en-us/windows/iot/Downloads
