### ISSUE TITLE
Write Filter feature prevents remote App updates (through Azure Blob)

### ISSUE THREAD

**Issue by bderuijsscher** [ms-iot/iot-adk-addonkit#266]
We are developing our device image with the inclusion of the Write Filter feature to make the target device more robust to sudden power failures. Our devices are managed through Azure IoT Hub (using the Azure IoT DM Client library).

As per the directions mentioned [(here)](https://docs.microsoft.com/en-us/windows/iot-core/secure-your-device/unifiedwritefilter), we have included several recommended exclusions.

However, these exclusions still prevent the updating of our custom application. This application update can be pushed through Azure IoT Hub and will perform and commit successfully when the Write Filter is disabled. With the Write Filter enabled, the app will update but this update will not persist after a reboot.

We have attempted to include the "U:\Programs\WindowsApps" folder (as well as its mounted C:\Data variant) as an additional exclusion, however after reboot the new app version refuses to start (probably because Windows is unable to find the "old" app package").

What would be the recommended solution to this problem?

**Comment by saraclay** [comment]
If this is still an issue, I encourage you to post this question in our forums, where we have dedicated staff there to help you out. Thank you.”
