### ISSUE TITLE
MinnoBoardMAX (MBM x64 and x86) build is non-functional

### ISSUE THREAD

**Issue by deepgray** [ms-iot/iot-adk-addonkit#269]
installoemcerts
buildpkg all
buildimage all

produces failures due to missing FeatureManifest files.

**Comment by parameshbabu** [comment]
See the above PR. You will need to use the BYT drivers from Intel (copy to your tree and run convert.cmd to patch the BYT packages).

**Comment by parameshbabu** [comment]
Closing.

**Comment by deepgray** [comment]
is x86 supported anymore or has everything gone x64?

**Comment by parameshbabu** [comment]
x86 is still supported but you will see more and more x64 platforms.
