### ISSUE TITLE
IoTOnboardingTask missing after creating image

### ISSUE THREAD

**Issue by endyb66** [ms-iot/iot-adk-addonkit#272]
When building a new image for the Dragonboard 410c, the IoTOnboardingTask is missing after flashing the image to the device. Instead the old AllJoyn app is there. I followed the guide on MSDN to build an image, did i miss something? Also the new IoTCoreDefaultApp is no there, still the older version only. But this will be updated to the newer one.

**Comment by parameshbabu** [comment]
The sample apps binaries have not been updated yet. While we update the binaries, you can replace them by rebuilding the corresponding projects from ms-iot/samples github.


________________________________

**Comment by endyb66** [comment]
The IoTCoreDefaultApp from MS-iot/samples is 11 months old, so it seems this also is the older one. Also the IoTOnboardingTask project seems to be an older one there.

**Comment by parameshbabu** [comment]
Are you referring to the SoftAP functionality, then you should include IOT_ONBOARDING_APP feature id. The sample doesn't contain this and i'll have that updated.

**Comment by endyb66** [comment]
Ok thank you.
