### ISSUE TITLE
Support for RS 5 1809 build

### ISSUE THREAD

**Issue by munsingh** [ms-iot/iot-adk-addonkit#273]
When will the iot-adk-addonkit be available for supporting RS5 (1809 build)?

**Comment by endyb66** [comment]
+1

**Comment by parameshbabu** [comment]
you can use the powershell branch. The docs will be updated shortly.

**Comment by munsingh** [comment]
Thanks for the quick turnaround @parameshbabu

**Comment by parameshbabu** [comment]
Closing.
