### ISSUE TITLE
Shouldn't the version be 10.1.17763.1 in ReadMe.md

### ISSUE THREAD

**Issue by munsingh** [ms-iot/iot-adk-addonkit#278]
The version listed in Branch Overview->Master Branch has the RS5 version listed as 10.0.17763.1. I believe it should be 10.1.17763.1.

**Comment by parameshbabu** [comment]
The OS version is 10.0.xx and the installed tools have 10.1.xx for some reason. 
OS version is better to be referred as if you access the version on the device, it will be 10.0.xx.
