### ISSUE TITLE
inf2cab.cmd replacement

### ISSUE THREAD

**Issue by munsingh** [ms-iot/iot-adk-addonkit#279]
Hello,

Couple of questions:

1. I was using inf2cab.cmd to generate the cab files for my hardware's driver. How do I do it now?
2. With the movement to powershell based scripts, is there any way I can still use the earlier commands (available with RS4) to generate IoT image for my hardware?

**Comment by parameshbabu** [comment]
Hi,

1. You can use newdrvpkg cmd and buildpkg cmd to get the cab files. I’ll soon add inf2cab cmd which will essentially call the above two cmd.
2. Most of the powershell cmd has alias same as old cmd tools , so you can still use old commands.

Regards,
Paramesh

________________________________

**Comment by parameshbabu** [comment]
inf2cab method added in powershell. See #280
