### ISSUE TITLE
How to create an ffu for the Dragonboard 410c eMMC that includes partitions for an SD card?

### ISSUE THREAD

**Issue by wtjerry** [ms-iot/iot-adk-addonkit#286]
So far i was able to create a ffu that contains my own custom partition layout. When this ffu is flashed to the internal storage of the 410c via the DragonboardUpdateTool, i can see the partitions with `wmic partition get /All`.
But those partitions are all on the internal storage.

Is it possible to specify a partition layout for the external SD card, so that both the internal eMMC partition layout and the external SD card partition layout are included in the ffu and applied when flashing the ffu?
Or do i need to manualy partition the SD card beforehand / partition it via scripts on first boot of the 410c?

How did i specify the partition layout?:
Create your own BSP and adapt the DeviceLayout package
![screenshot from 2018-10-14 12-25-08](https://user-images.githubusercontent.com/15376943/46915467-57d98d80-cfac-11e8-8d75-03ea43473fcd.png)

Thanks in advance

**Comment by parameshbabu** [comment]
the FFU targets the internal eMMC device only. You will need to manually partition the SD card via scripts on first boot ( see OEMCustomizations.cmd ).
