### ISSUE TITLE
Error: IoT Core kit ver not found in registry

### ISSUE THREAD

**Issue by alexismichellyc** [ms-iot/iot-adk-addonkit#294]
![iot problem](https://user-images.githubusercontent.com/33688557/49191952-21e44300-f379-11e8-97eb-258ebd10bb0c.png)
Installed everything from scratch, as mentionned in the IOT Core manufacturing guide.
As soon as I open the Powershell IoTCorePShell I get this error message : Error: IoT Core kit ver not found in registry. Not sure what to do here.

**Comment by parameshbabu** [comment]
This occurs when you have not installed IoT Core packages (ARM version). If you have installed the amd64 version, then you can ignore this and when you do setenv amd64, proper status will show up.

I'll look to improve this message further.

**Comment by parameshbabu** [comment]
with #295 you should see what arch packages are installed on the first launch.
Closing this.
