### ISSUE TITLE
Question: When is the plan to release the toolkit for 17763 version? It is currently in Master Branch.

### ISSUE THREAD

**Issue by majidshaffi** [ms-iot/iot-adk-addonkit#298]

**Comment by HalHunt** [comment]
I have the same question.  We need to build a new custom FFU ASAP.  Thank you.

**Comment by parameshbabu** [comment]
Hi
You can use the master branch as is and build images.
The older release are baselined when a new release is available.

17763 is the current supported version on the master branch.

Regards,
Paramesh

________________________________

**Comment by HalHunt** [comment]
Thank you for your quick response Paramesh, however based on the current documentation and the contents of this repo it's not clear to me where I get the BSP files from.  Any guidance is greatly appreciated.

**Comment by parameshbabu** [comment]
For the BSPs, see this link : https://docs.microsoft.com/en-us/windows-hardware/manufacture/iot/bsphardware

Regards,
Paramesh

________________________________

**Comment by parameshbabu** [comment]
The RPi bsp can be used for 17763 also. BSP is not dependent on OS release.

Regards,
Paramesh

________________________________
