### ISSUE TITLE
OEM app not present in FFU image on RPi 3

### ISSUE THREAD

**Issue by Granathar** [ms-iot/iot-adk-addonkit#317]
I recently updated AddonKit from a little bit older version, created new WS just like before. Everything seems to be fine, image is being built, BUT it appears to be clean Win10 IoT without any default app, because I removed all sample apps from TestOEMInput.xml. My custom OEM application is added in OEM section, just like it was added with older AddonKit and seems missing (it was fine before). RPi boots normally, but as there is no default app it just shows black screen.

My feature section from TestOEMInput.xml looks like that:

```
<Features>
    <Microsoft>
      <Feature>IOT_EFIESP</Feature>
      <Feature>IOT_EFIESP_BCD_MBR</Feature>
      <Feature>IOT_DMAP_DRIVER</Feature>
      <Feature>IOT_CP210x_MAKERDRIVER</Feature>
      <Feature>IOT_FTSER2K_MAKERDRIVER</Feature>
      <Feature>IOT_GENERIC_POP</Feature>
      <!-- Following two required for Appx Installation -->
      <Feature>IOT_UAP_OOBE</Feature>
      <Feature>IOT_APP_TOOLKIT</Feature>
      <!-- for Connectivity -->
      <Feature>IOT_WEBB_EXTN</Feature>
      <Feature>IOT_POWERSHELL</Feature>
      <Feature>IOT_SSH</Feature>
      <Feature>IOT_SIREP</Feature>
      <!-- Enabling Test images -->
      <Feature>IOT_ENABLE_TESTSIGNING</Feature>
      <Feature>IOT_TOOLKIT</Feature>
      <!-- Debug Features -->
      <Feature>IOT_KDSERIAL_SETTINGS</Feature>
      <Feature>IOT_UMDFDBG_SETTINGS</Feature>
      <Feature>IOT_WDTF</Feature>
      <Feature>IOT_CRT140</Feature>
      <Feature>IOT_DIRECTX_TOOLS</Feature>
    </Microsoft>
    <OEM>
      <!-- Include BSP Features -->
      <Feature>RPI2_DRIVERS</Feature>
      <Feature>RPI3_DRIVERS</Feature>
      <!-- Include OEM features -->
      <Feature>OEM_CustomCmd</Feature>
      <Feature>OEM_ProvAuto</Feature>
      <!-- For recovery, include: RECOVERY_BCD_MBR -->
      <Feature>APPX_OEMPLACEHOLDER</Feature>
    </OEM>
  </Features>
```

**Comment by IsmailHassani** [comment]
Check this [https://social.msdn.microsoft.com/Forums/en-US/5e69a7eb-b8f6-4ac8-a150-025e7d045842/uwp-application-is-not-installed?forum=WindowsIoT](https://social.msdn.microsoft.com/Forums/en-US/5e69a7eb-b8f6-4ac8-a150-025e7d045842/uwp-application-is-not-installed?forum=WindowsIoT) where i had the same issue. Maybe it helps
