### ISSUE TITLE
Warning: IOT_GENERIC_POP is not defined

### ISSUE THREAD

**Issue by trivalik** [ms-iot/iot-adk-addonkit#318]
I want to create a retail image with ```New-IoTFFUImage xxx Retail```. By default is "IOT_GENERIC_POP" defined. But I get the warning "IOT_GENERIC_POP is not defined". Then I removed this line from the retail xml, and the warning was gone. So I guess the word ```not``` is here too much.

**Comment by parameshbabu** [comment]
This error essentially highlights that the feaure identifier used in the xml is not defined. 
For this specific issue, the fix is to remove this feature id as this has been deprecated in the last release.
