### ISSUE TITLE
Windows IOT Intel - BYTx64FM.xml not found

### ISSUE THREAD

**Issue by ZejotnA** [ms-iot/iot-adk-addonkit#319]
Hello, I have to build an Windows IOT image for a 64-bit processor. When i run the "buildimage" command, i have this error : 
![image](https://user-images.githubusercontent.com/51236265/58707751-0ef90c80-83b6-11e9-8a1c-e61143f8c39f.png)

I tried to execute it too on x86 but there is the same error.
The BYTx64FM.xml is not found but he is present in the folder...

![image](https://user-images.githubusercontent.com/51236265/58707947-a1011500-83b6-11e9-9df8-670faf2c6cc6.png)

I have followed instruction of this website : https://sibeeshpassion.com/raspberry-pi-sd-card-provisioning-with-windows-10-iot-core-create-ffu-image-and-flash/#prerequisites

But with Intel BSP : https://downloadcenter.intel.com/download/25618/Intel-Embedded-Drivers-for-Microsoft-Windows-10-IoT-Core-32-bit-and-64-bit-MR1?product=29035

Could you help me ?

**Comment by parameshbabu** [comment]
Hi,

Can you follow the instructions for Intel BSP here
https://docs.microsoft.com/en-us/windows-hardware/manufacture/iot/bsphardware#intel-bsps

Regards,
Paramesh
________________________________

**Comment by ZejotnA** [comment]
Thank's a lot !
It works! 
Have a good day!
