### ISSUE TITLE
Windows 10 IOT Problem - BYTx64FM.xml not found

### ISSUE THREAD

**Issue by Takaao1** [ms-iot/iot-adk-addonkit#320]
Hello, i have a problem when I try to build an image for a computer who has a x64 processor INTEL.

I'm trying to build an image for a x64 processor, but i don't know why i have this error, by the way i have this file in the folder.
Could you please help me ? I have past a lot of hours trying to find why I have this error.
( I have installed ADK + WDK latest versions, adk-addonkit too)
![image](https://user-images.githubusercontent.com/43552973/58708745-dc9cde80-83b8-11e9-8872-7e27a523e10c.png)

**Comment by parameshbabu** [comment]
Hi,

Can you follow the instructions for Intel BSP here
https://docs.microsoft.com/en-us/windows-hardware/manufacture/iot/bsphardware#intel-bsps

Regards,
Paramesh
________________________________

**Comment by Takaao1** [comment]
Geat, it works! 
Thank you very much
