### ISSUE TITLE
createpkg can't be run in build servers

### ISSUE THREAD

**Issue by baget** [ms-iot/iot-adk-addonkit#46]
Normal users without the right permission can't use createpkg to build driver packages, e.g. in Build and CI Servers

Getting:
`DriverStoreOpen failed error 0x00000522`

**Comment by parameshbabu** [comment]
You do require administrator rights to work with imaging tools (the IoTCoreShell is run in the elevated prompt always for this reason). 
Can you provide more details on what you are trying to do?

**Comment by baget** [comment]
trying to build a cab package from my driver package.
why for building cab package  need elevated prompt?

**Comment by parameshbabu** [comment]
Building driver cab needs access to the driver store and this needs admin rights. This is by design.
