### ISSUE TITLE
binexport ??

### ISSUE THREAD

**Issue by dvescovi1** [ms-iot/iot-adk-addonkit#52]
directions for building BSP drivers do not make any sense.
what tools directory are you referring too? 
There is no binexport file.

**Comment by parameshbabu** [comment]
the PR for the ms-iot/bsp project is still open. You will have this once that PR in integrated in the ms-iot/bsp project.

**Comment by parameshbabu** [comment]
the PR for ms-iot/bsp is now merged. Please check and feedback if you are able to create the packages. Thanks.

**Comment by dvescovi1** [comment]
works great
