### ISSUE TITLE
RetailOEMInput.xml must not use _TEST packages

### ISSUE THREAD

**Issue by tiagoshibata** [ms-iot/iot-adk-addonkit#57]
Building an image with [Source-arm/BSP/QCDB410C/OEMInputSamples/RetailOEMInput.xml](https://github.com/ms-iot/iot-adk-addonkit/blob/1cb9599df6d8c6299825de87e2422396051bbf61/Source-arm/BSP/QCDB410C/OEMInputSamples/RetailOEMInput.xml) generates an invalid image because `_TEST` packages are being used with `ReleaseType = Production`. [These lines should have _TEST removed.](https://github.com/ms-iot/iot-adk-addonkit/blob/1cb9599df6d8c6299825de87e2422396051bbf61/Source-arm/BSP/QCDB410C/OEMInputSamples/RetailOEMInput.xml#L37-L52)

**Comment by parameshbabu** [comment]
Fixed.
