### ISSUE TITLE
IoT Core Version question

### ISSUE THREAD

**Issue by weipah** [ms-iot/iot-adk-addonkit#58]
Hi,

is it correct that at the moment with the iot-adk-addonkit and the correspondig IoT Core Packages available today we can only build custom images with IoT build version 14393?

There is no way I can get a custom image for an insider preview version like 15051, right?

**Comment by IoTGirl** [comment]
Hi Weipah,
It is my understanding that custom commercial images can only be built using release builds, like 14393 and that is the only scenario supported through this GitHub.  However, if you are a Windows Insider you can get intermediate tooling like "https://www.microsoft.com/en-us/software-download/windowsinsiderpreviewADK" but your mileage may vary and all issue with the insider ADK should be reported through that program.
Sincerely,
IoTGirl
