### ISSUE TITLE
1703 supported, do I generate 1703 error

### ISSUE THREAD

**Issue by Yuexs** [ms-iot/iot-adk-addonkit#90]
1703 supported, do I generate 1703 error

**Comment by IoTGirl** [comment]
Hi @Yuexs,
Can you please explain what error you get and how you get it?
Sincerely,
IoTGirl

**Comment by Yuexs** [comment]
ADK 1703,iot-adk-addonkit 1703 Error when creating image, but reinstall ADK 14393,iot-adk-addonkit 14393 is normal

**Comment by Yuexs** [comment]
I'm creating a raspberry pie 3B image

**Comment by IoTGirl** [comment]
This is really not enough information @Yuexs.  Can you please provide more details as to your setup?

**ENVIRONMENT:**
What Computers, OS, tools and devices are involved with this repro? How are they connected? What versions?

**REPRO STEPS:**
What steps would someone else need to follow to see the issue?

**RESULTS:**
What did you Expect to happen?
What did Actually happen?

**NOTES:**
Any other details/workarounds potentially related info

**Comment by IoTGirl** [comment]
Closing due to lack of response: Please see [https://social.msdn.microsoft.com/Forums/en-US/home?forum=WindowsIoT](https://social.msdn.microsoft.com/Forums/en-US/home?forum=WindowsIoT) for other build issues and their solutions
